filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/local/nginx/logs/access.log
  json.keys_under_root: true
  json.overwrite_keys: true
  fields:
    log_app: nginx
    log_topics: nginx_access_logs

output.kafka:
  enabled: true
  hosts: ["kafka-0.kafka-svc:9092"]
  topic: '%{[fields][log_topics]}'
  compression: gzip
