apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-cm
  namespace: monitoring
  labels:
    name: zookeeper
    app: elk
data:
  zoo.cfg: |
    dataDir=/data
    dataLogDir=/datalog
    tickTime=2000
    initLimit=10
    syncLimit=5
    autopurge.snapRetainCount=3
    autopurge.purgeInterval=0
    maxClientCnxns=60
    standaloneEnabled=false
    admin.enableServer=false
    server.0=zookeeper-0-0.zookeeper-svc:2888:3888;2181
    server.1=zookeeper-1-0.zookeeper-svc:2888:3888;2181
    server.2=zookeeper-2-0.zookeeper-svc:2888:3888;2181
