apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-cm
  namespace: app
data:
  zoo.cfg: |
    dataDir=/data
    dataLogDir=/datalog
    tickTime=2000
    initLimit=10
    syncLimit=5
    autopurge.snapRetainCount=3
    autopurge.purgeInterval=0
    maxClientCnxns=60
    standaloneEnabled=false
    admin.enableServer=false
    server.1=zookeeper-0.zookeeper-svc:2888:3888;2181
