apiVersion: v1
kind: Service
metadata:
  name: zookeeper-svc
  namespace: app
  labels:
    name: zookeeper
    app: elk
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: client
    port: 2181
    targetPort: 2181
  - name: follower
    port: 2888
    targetPort: 2888
  - name: election
    port: 3888
    targetPort: 3888
  selector:
    name: zookeeper