apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: app
  labels:
    name: kibana
    app: elk
spec:
  selector:
    name: kibana
  type: ClusterIP
  ports:
    - port: 5601
      targetPort: 5601