apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-cm
  namespace: monitoring
  labels:
    name: kibana
    app: elk
data:
  kibana.yml: |
    server.port: 5601
    server.host: "0.0.0.0"
    elasticsearch.hosts: ["http://elasticsearch-0-0.elasticsearch-svc:9200"]
    elasticsearch.username: "kibana"
    elasticsearch.password: "Fhvkeg12AgDQtodyXbje"
    elasticsearch.requestTimeout: 100000
    xpack.monitoring.ui.container.elasticsearch.enabled: true
    i18n.locale: "zh-CN"
    # 开启kibana网站URI重写
    server.rewriteBasePath: true
    server.basePath: "/elk"
