apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: monitoring
  labels:
    name: kibana
    app: elk
spec:
  selector:
    name: kibana
  type: NodePort
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30561
