apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-cm
  namespace: app
data:
  elasticsearch.yml: |
    cluster.name: qiufeng-elk
    node.name: "${POD_NAME}.elasticsearch-svc"
    network.host: 0.0.0.0
    http.port: 9200
    transport.tcp.port: 9300
    node.master: true
    node.data: true
    discovery.zen.ping_timeout: 180s
    cluster.initial_master_nodes: ["elasticsearch-0.elasticsearch-svc"]
    bootstrap.system_call_filter: false
    
    # 如果elasticsearch副本数有多个，那就需要写入多个。例如副本数为3个
    #discovery.seed_hosts: ["elasticsearch-0.elasticsearch-svc","elasticsearch-1.elasticsearch-svc","elasticsearch-2.elasticsearch-svc"]
    #discovery.zen.minimum_master_nodes: 2