apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: app
  labels:
    name: elasticsearch
    app: elk
spec:
  replicas: 1
  # 设置service的名称
  serviceName: elasticsearch-svc
  selector:
    matchLabels:
      name: elasticsearch
  template:
    metadata:
      labels:
        name: elasticsearch
        app: elk
    spec:
      # 调度策略，匹配存在app=elk标签的nodes
      nodeSelector:
        app: elk
      # 初始化容器，修改系统参数
      initContainers:
      - name: increase-vm-max-map
        image:  busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        imagePullPolicy: IfNotPresent
        image:  busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
      # elasticsearch容器配置
      containers:
      - name: elasticsearch
        imagePullPolicy: IfNotPresent
        image: elasticsearch:7.14.2
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ES_JAVA_OPTS
          value: "-Xms900m -Xmx900m"
      # 设置容器端口
        ports:
        - name: api
          containerPort: 9200
        - name: inter-node
          containerPort: 9300
      # 资源限制
        resources:
          limits:
            cpu: 1000m
            memory: 1500Mi
          requests:
            cpu: 500m
            memory: 500Mi
      # 健康检测
        livenessProbe:
          tcpSocket:
            port: 9200
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
      # 就绪检测
        readinessProbe:
          tcpSocket:
            port: 9200
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
      # 容器路径挂载
        volumeMounts:
        - name: es-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
      # configmap资源挂载
      volumes:
      - name: es-config
        configMap:
          name: elasticsearch-cm
  # storageClass资源自动创建PVC及绑定
  volumeClaimTemplates:
  - metadata:
      name: es-data
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: nfs-storage
      resources:
        requests:
          storage: 8Gi
