apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: app
  labels:
    name: logstash
    app: elk
spec:
  selector:
    name: logstash
  type: ClusterIP
  ports:
    - port: 5044
      targetPort: 5044
